Repository SansamForce/team-building, pull requests merged in 2024-10, with the labels that each got.

#176 [REFACTOR] 프로젝트 컨트롤러 ResponseEntity 응답 방식 수정
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectBoardController.java
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectController.java
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectMemberController.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectApplyMemberController.java
Labels: REFACTOR

#182 [REFACTOR] 프로젝트 컨트롤러 엔드포인트 수정
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectMemberController.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/application/dto/AdminProjectApplyMemberDTO.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectApplyMemberMapper.java
  team/src/main/java/sansam/team/project/query/controller/AdminProjectBoardQueryController.java
  team/src/main/java/sansam/team/project/query/controller/AdminProjectMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectApplyMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectMentorReviewQueryController.java
Labels: REFACTOR

#183 [REFACTOR] 마이페이지 수정 기능 리펙토링
  team/src/main/java/sansam/team/user/command/application/controller/UserController.java
  team/src/main/java/sansam/team/user/command/application/dto/UserUpdateRequestDTO.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
Labels: REFACTOR

#185 [FEAT] 강사평가 계산 로직 추가
  team/src/main/java/sansam/team/common/github/GithubUtil.java
  team/src/main/java/sansam/team/project/command/domain/repository/ProjectMentorReviewRepository.java
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
  team/src/main/java/sansam/team/team/command/domain/repository/TeamReviewRepository.java
  team/src/main/resources/data.sql
Labels: FEAT

#191 feat/team/#190
  team/src/main/java/sansam/team/team/command/application/controller/TeamController.java
  team/src/main/java/sansam/team/team/command/application/service/TeamService.java
  team/src/main/java/sansam/team/team/query/controller/TeamQueryController.java
  team/src/main/java/sansam/team/team/query/dto/TeamFindByIdResponse.java
  team/src/main/java/sansam/team/team/query/dto/TeamMemberResponse.java
  team/src/main/java/sansam/team/team/query/dto/TeamQueryDTO.java
  team/src/main/java/sansam/team/team/query/dto/TeamRequest.java
  team/src/main/java/sansam/team/team/query/dto/TeamResponse.java
  team/src/main/java/sansam/team/team/query/dto/TeamScheduleResponse.java
  team/src/main/java/sansam/team/team/query/mapper/TeamQueryMapper.java
  team/src/main/java/sansam/team/team/query/service/TeamQueryService.java
  team/src/main/resources/mapper/team/TeamMapper.xml
Labels: FEAT

#199 [REFACTOR] 프로젝트 READ 컨트롤러 응답 반환 값 변경 작업
  team/src/main/java/sansam/team/project/query/controller/AdminProjectBoardQueryController.java
  team/src/main/java/sansam/team/project/query/controller/AdminProjectMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/AdminProjectQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectApplyMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectMentorReviewQueryController.java
Labels: REFACTOR

#198 [REFACTOR] 모든 컨트롤러 엔드포인트 일부 수정
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatMessageController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberScheduleController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamScheduleController.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamScheduleQueryController.java
  team/src/main/java/sansam/team/user/command/application/controller/UserGithubRepositoryController.java
  team/src/main/java/sansam/team/user/query/controller/UserGithubRepositoryQueryController.java
  team/src/main/java/sansam/team/user/query/controller/UserInfoQueryController.java
Labels: REFACTOR

#201 [REFACTOR] 팀 도메인 컨트롤러 ResponseApi 응답 값으로 변경 작업
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingRuleController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberScheduleController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamScheduleController.java
  team/src/main/java/sansam/team/team/query/controller/TeamBuildingRuleQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatMemberQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamScheduleQueryController.java
  team/src/main/java/sansam/team/user/query/controller/UserInfoQueryController.java
  team/src/main/java/sansam/team/user/query/service/UserInfoQueryService.java
Labels: REFACTOR

#207 [CHORE]#204_userAuth 추가
  team/src/main/java/sansam/team/security/handler/LoginSuccessHandler.java
  team/src/main/java/sansam/team/security/util/SecurityUtil.java
  team/src/main/java/sansam/team/team/command/application/service/TeamMemberScheduleService.java
  team/src/main/java/sansam/team/user/query/service/UserDetailServiceImpl.java
Labels: CHORE

#218 [DOCS] readme 수정
  README.md
  img.png
  img_2.png
  img_3.png
Labels: DOCS

#219 [REFACTOR] TEAM entity 생성자 access 변경
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/Team.java
  team/src/test/java/sansam/team/team/command/application/service/TeamServiceTest.java
Labels: REFACTOR

#225 [REFACTOR] 팀 빌딩 강사 제외 코드 수정 및 데이터 insert문 수정
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
  team/src/main/java/sansam/team/user/query/dto/UserQueryDTO.java
  team/src/main/resources/data.sql
Labels: REFACTOR

#233 [CHORE] team 코드 정리
  team/src/main/java/sansam/team/team/command/application/dto/TeamReviewDTO.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamScheduleDTO.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/Team.java
Labels: CHORE

#237 [BUG] 팀 리스트 조회 수정
  team/src/main/java/sansam/team/team/query/controller/TeamQueryController.java
  team/src/main/java/sansam/team/team/query/mapper/TeamQueryMapper.java
  team/src/main/java/sansam/team/team/query/service/TeamQueryService.java
  team/src/main/resources/mapper/team/TeamMapper.xml
Labels: BUG

#241 버그수정
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
  team/src/main/resources/data.sql
Labels: BUG

#248 [BUG] JPA 컬럼 삭제
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/LoginLog.java
  team/src/main/resources/mapper/user/AdminUserQueryMapper.xml
Labels: BUG

#249 [FEAT] 관리자 회원 조회 기능 구현
  team/src/main/java/sansam/team/user/query/controller/AdminUserInfoQueryController.java
  team/src/main/java/sansam/team/user/query/controller/UserQueryController.java
  team/src/main/java/sansam/team/user/query/dto/AdminUserInfoAllQueryDTO.java
  team/src/main/java/sansam/team/user/query/dto/AdminUserInfoQueryDTO.java
  team/src/main/java/sansam/team/user/query/mapper/AdminUserInfoQueryMapper.java
  team/src/main/java/sansam/team/user/query/service/AdminUserInfoQueryService.java
  team/src/main/resources/mapper/user/AdminUserInfoQueryMapper.xml
Labels: FEAT

#251 [FEAT] 관리자 회원 정보 수정 기능 구현
  team/src/main/java/sansam/team/user/command/application/controller/AdminUserController.java
  team/src/main/java/sansam/team/user/command/application/dto/AdminUserUpdateRequestDTO.java
  team/src/main/java/sansam/team/user/command/application/service/AdminUserService.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/java/sansam/team/user/command/domain/repository/AdminUserRepository.java
  team/src/main/java/sansam/team/user/command/infrastructure/repository/JpaAdminUserRepository.java
  team/src/main/java/sansam/team/user/query/controller/AdminUserInfoQueryController.java
Labels: FEAT

#255 [REFACTOR] 마이페이지 조회, 수정 내용 추가 작업
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
  team/src/main/java/sansam/team/user/command/application/dto/UserUpdateRequestDTO.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/java/sansam/team/user/query/dto/UserInfoResponseDTO.java
  team/src/main/resources/mapper/user/UserInfoQueryMapper.xml
  team/src/main/resources/schema.sql
Labels: REFACTOR

#258 [REFACTOR] pathvariable 추가 및 엔드포인트 수정 작업
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectMemberController.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectMentorReviewController.java
  team/src/main/java/sansam/team/project/command/application/dto/AdminProjectApplyMemberDTO.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
  team/src/main/java/sansam/team/project/query/controller/ProjectApplyMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectMentorReviewQueryController.java
  team/src/main/java/sansam/team/project/query/dto/AdminProjectMemberAllQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/ProjectApplyMemberQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewAllUserQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewUserQueryDTO.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingRuleController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberScheduleController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamScheduleController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamMemberScheduleDTO.java
  team/src/main/java/sansam/team/team/command/application/service/TeamMemberScheduleService.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMemberSchedule.java
  team/src/main/java/sansam/team/team/query/controller/TeamBuildingRuleQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatQueryController.java
  team/src/main/java/sansam/team/user/command/application/controller/UserGithubRepositoryController.java
  team/src/main/java/sansam/team/user/command/application/dto/UserGithubRepositoryDTO.java
  team/src/main/java/sansam/team/user/command/application/service/UserGithubRepositoryService.java
  team/src/main/java/sansam/team/user/command/mapper/UserGithubRepositoryMapper.java
  team/src/main/java/sansam/team/user/query/dto/UserGithubRepositoryQueryDTO.java
  team/src/main/resources/mapper/project/ProjectBoardMapper.xml
  team/src/main/resources/mapper/project/ProjectMember.xml
  team/src/main/resources/mapper/project/ProjectMentorReviewMapper.xml
  team/src/main/resources/mapper/user/UserGithubRepositoryQueryMapper.xml
  team/src/main/resources/schema.sql
Labels: FEAT, REFACTOR

#262 [FEAT] CORS 적용
  team/src/main/java/sansam/team/config/WebConfig.java
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
Labels: FEAT

#263 [REFACTOR] 팀 빌딩 로직 수정
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamBuildingResultDTO.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamMemberScoreDTO.java
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
  team/src/main/resources/data.sql
Labels: REFACTOR

#265 [REFACTOR] 자동 팀 빌딩 기능 수정
  team/src/main/java/sansam/team/team/command/application/dto/TeamMemberScoreDTO.java
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
  team/src/main/resources/data.sql
Labels: CHORE, REFACTOR

#268 [FEAT] 팀 추가 기능 구현
  team/src/main/java/sansam/team/team/command/application/controller/TeamController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatMessageDeleteRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamCreateRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamDTO.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamUpdateRequest.java
  team/src/main/java/sansam/team/team/command/application/service/TeamService.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/Team.java
  team/src/main/java/sansam/team/team/command/mapper/TeamMapper.java
  team/src/main/resources/schema.sql
Labels: FEAT, REFACTOR

#269 [FEAT] 회원 평가 조회 기능 구현
  team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
  team/src/main/java/sansam/team/team/query/controller/TeamUserReviewQueryController.java
  team/src/main/java/sansam/team/team/query/dto/TeamUserReviewAllQueryDTO.java
  team/src/main/java/sansam/team/team/query/dto/TeamUserReviewQueryDTO.java
  team/src/main/java/sansam/team/team/query/mapper/TeamUserReviewQueryMapper.java
  team/src/main/java/sansam/team/team/query/service/TeamUserReviewQueryService.java
  team/src/main/resources/mapper/team/TeamUserReviewMapper.xml
Labels: FEAT, REFACTOR

#273 [FEAT] S3 이미지 업로드 작업 완료
  team/src/main/java/sansam/team/config/OctetStreamReadMsgConverter.java
  team/src/main/java/sansam/team/config/WebConfig.java
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectBoardController.java
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectController.java
  team/src/main/java/sansam/team/project/command/application/dto/AdminProjectBoardUpdateDTO.java
  team/src/main/java/sansam/team/project/command/application/dto/AdminProjectUpdateDTO.java
  team/src/main/java/sansam/team/project/command/application/service/AdminProjectBoardService.java
  team/src/main/java/sansam/team/project/command/application/service/AdminProjectService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/Project.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectBoard.java
  team/src/main/java/sansam/team/user/command/application/controller/UserController.java
  team/src/main/java/sansam/team/user/command/application/service/UserService.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/resources/schema.sql
Labels: FEAT, CHORE, REFACTOR

#279 [REFACTOR] 스프링 시큐리티 설정 변경
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
  team/src/main/java/sansam/team/security/handler/LoginFailureHandler.java
Labels: REFACTOR

#281 [REFACTOR] 컬럼 길이 수정
  team/src/main/resources/schema.sql
Labels: REFACTOR

#283 [REFACTOR] 프로젝트 게시글 신청 회원 seq 값 잘못 들어가는 이슈 해결
  team/src/main/java/sansam/team/project/command/application/service/AdminProjectBoardService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
Labels: BUG, REFACTOR

#285 [FEAT] 프로젝트 게시물 신청 회원 관심분야 추가
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectApplyMemberMapper.java
Labels: FEAT

#287 [BUG] 프로젝트 신청 취소 기능 cast 수정
  team/src/main/java/sansam/team/project/command/application/service/ProjectApplyMemberService.java
Labels: BUG

#288 [BUG] 프로젝트 신청 취소 파라미터 수정
  team/src/main/java/sansam/team/project/command/application/controller/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/domain/repository/ProjectApplyMemberRepository.java
  team/src/main/java/sansam/team/project/query/dto/ApplyMemberQueryDTO.java
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
  team/src/main/resources/mapper/project/ProjectApplyMemberMapper.xml
Labels: BUG

#289 [BUG] 신청목록에 게시글 seq 추가
  team/src/main/java/sansam/team/project/query/dto/ApplyMemberQueryDTO.java
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
  team/src/main/resources/mapper/project/ProjectApplyMemberMapper.xml
Labels: BUG

#291 [REFACTOR] 관리자 회원 정보 조회, 수정 누락 내용 추가
  team/src/main/java/sansam/team/user/command/application/dto/AdminUserUpdateRequestDTO.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/java/sansam/team/user/query/dto/AdminUserInfoQueryDTO.java
  team/src/main/resources/mapper/user/AdminUserInfoQueryMapper.xml
Labels: REFACTOR

#293 [REFACTOR] 프로젝트 신청 회원 추가 응답 값 추가
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectBoardController.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/application/dto/ProjectApplyMemberRequestDTO.java
  team/src/main/java/sansam/team/project/command/application/dto/ProjectApplyMemberResponseDTO.java
  team/src/main/java/sansam/team/project/command/application/service/AdminProjectBoardService.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectApplyMemberMapper.java
Labels: FEAT, REFACTOR

#295 [FEAT] 프로젝트 게시글 모집 기간 추가
  team/src/main/java/sansam/team/project/query/dto/ProjectBoardDTO.java
  team/src/main/resources/mapper/project/ProjectBoardMapper.xml
Labels: FEAT

#297 [REFACTOR] 시큐리티 비회원 엔드포인트 확장
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
Labels: REFACTOR

#299 [REFACTOR] 팀 채팅 기능 프론트에 맞게 리팩토링
  team/src/main/java/sansam/team/common/websocket/dto/TeamChatMemberDTO.java
  team/src/main/java/sansam/team/common/websocket/dto/TeamChatMessageDTO.java
  team/src/main/java/sansam/team/common/websocket/handler/WebSocketChatHandler.java
  team/src/main/java/sansam/team/security/filter/JWTFilter.java
  team/src/main/java/sansam/team/team/query/dto/TeamFindByIdResponse.java
  team/src/main/java/sansam/team/team/query/service/TeamChatQueryService.java
  team/src/main/resources/mapper/team/TeamMapper.xml
Labels: FEAT, REFACTOR

#304 [FEAT] 채팅 구현 완료
  team/src/main/java/sansam/team/common/websocket/WebSocketClient.java
  team/src/main/java/sansam/team/common/websocket/handler/WebSocketChatHandler.java
  team/src/main/java/sansam/team/project/query/dto/ProjectQueryDTO.java
  team/src/main/java/sansam/team/team/query/dto/TeamChatResponse.java
  team/src/main/java/sansam/team/team/query/dto/TeamChatRoomResponse.java
  team/src/main/java/sansam/team/team/query/service/TeamChatQueryService.java
  team/src/main/resources/mapper/team/TeamMapper.xml
Labels: FEAT

#306 [BUG] 프로젝트 게시글 생성 dto 수정
  team/src/main/java/sansam/team/project/command/application/dto/AdminProjectBoardCreateDTO.java
Labels: BUG

#311 [CHORE] 프로젝트 생성 DTO response body 수정
  team/src/main/java/sansam/team/project/command/application/controller/AdminProjectMemberController.java
  team/src/main/java/sansam/team/project/command/application/dto/ProjectMemberAddDTO.java
  team/src/main/java/sansam/team/project/command/application/service/AdminProjectMemberService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectMemberMapper.java
  team/src/main/java/sansam/team/project/query/dto/ProjectApplyMemberQueryDTO.java
Labels: REFACTOR

#313 [REFACTOR] 프로젝트 상세조회 teamSeq 삭제
  team/src/main/java/sansam/team/project/query/dto/ProjectQueryDTO.java
  team/src/main/resources/mapper/project/ProjectMapper.xml
Labels: REFACTOR

#317 [REFACTOR] 프로젝트 신청 회원 엔드포인트 변경
  team/src/main/java/sansam/team/project/query/controller/ProjectApplyMemberQueryController.java
Labels: REFACTOR

#320 [FEAT] 강사 프로젝트 조회 시 프로젝트 멤버 조회 기능 구현
  team/src/main/java/sansam/team/project/query/controller/ProjectMemberQueryController.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMemberQueryDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectQueryService.java
  team/src/main/resources/mapper/project/ProjectMapper.xml
Labels: FEAT

#323 [REFACTOR] 세큐리티 프로젝트 회원 조회 수정
  team/src/main/java/sansam/team/security/config/SecurityConfig.java
Labels: REFACTOR

#325 [REFACTOR] 팀 조회 시 프로젝트 SEQ를 이용하여 조회
  team/src/main/java/sansam/team/team/query/controller/TeamQueryController.java
  team/src/main/java/sansam/team/team/query/dto/TeamRequest.java
  team/src/main/java/sansam/team/team/query/service/TeamQueryService.java
  team/src/main/resources/mapper/team/TeamMapper.xml
Labels: REFACTOR

#329 [REFACTOR] 팀 빌딩 규칙 생성 반환 DTO생성
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingRuleController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamBuildingRuleResponseDTO.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamBuildingRule.java
Labels: REFACTOR

#331 [REFACTOR] 팀 빌딩 알고리즘 수정
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
Labels: REFACTOR

#333 [REFACTOR] 팀 채팅 조회 조건 변경
  team/src/main/java/sansam/team/team/query/dto/TeamChatRoomRequest.java
  team/src/main/java/sansam/team/team/query/service/TeamChatQueryService.java
  team/src/main/resources/mapper/team/TeamChatMapper.xml
  team/src/main/resources/mapper/team/TeamMapper.xml
Labels: REFACTOR

#343 [REFACTOR] 강사 평가 조회 API 변경 작업
  team/src/main/java/sansam/team/project/query/controller/ProjectMentorReviewQueryController.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewQueryDTO.java
  team/src/main/resources/mapper/project/ProjectMentorReviewMapper.xml
Labels: REFACTOR
