Repository SansamForce/team-building, pull requests merged in 2024-09, with the labels that each got.

#4 [FEAT] Swagger 연동 및 설정 파일 추가
  team/build.gradle
  team/compose.yaml
  team/docker-compose.yml
  team/src/main/java/sansam/team/Application.java
  team/src/main/java/sansam/team/config/SwaggerConfig.java
  team/src/main/resources/application.properties
  team/src/main/resources/application.yml
Labels: FEAT, CHORE

#6 [FEAT] docker-compose 설정 및 Mysql 연동
  .gitignore
  docker-compose.yml
  team/docker-compose.yml
  team/src/main/resources/application.yml
Labels: FEAT

#8 [FEAT] JPA 연동 및 테스트 코드 추가
  .gitignore
  team/build.gradle
  team/src/main/java/sansam/team/config/WebConfig.java
  team/src/main/java/sansam/team/test/command/controllers/TestController.java
  team/src/main/java/sansam/team/test/command/entities/Test.java
  team/src/main/java/sansam/team/test/command/repositories/TestRepository.java
  team/src/main/java/sansam/team/test/command/services/TestDTO.java
  team/src/main/java/sansam/team/test/command/services/TestService.java
  team/src/test/java/sansam/team/test/command/services/TestServiceTest.java
Labels: FEAT

#10 [FEAT] Mybatis 연동 및 테스트 코드 추가
  team/build.gradle
  team/src/main/java/sansam/team/config/MybatisConfig.java
  team/src/main/java/sansam/team/test/query/controllers/TestQueryController.java
  team/src/main/java/sansam/team/test/query/mappers/TestMapper.java
  team/src/main/java/sansam/team/test/query/servicies/TestQueryDTO.java
  team/src/main/java/sansam/team/test/query/servicies/TestQueryService.java
  team/src/main/resources/sansam/team/test/query/mappers/TestMapper.xml
  team/src/test/java/sansam/team/test/query/services/TestQueryServiceTest.java
Labels: FEAT

#12 [FEAT] 테스트 완료
  team/src/main/java/sansam/team/config/SwaggerConfig.java
Labels: FEAT

#16 [FEAT] S3 연동 및 테스트 코드 작성 완료
  docker-compose.yml
  team/build.gradle
  team/src/main/java/sansam/team/common/FileUploadDTO.java
  team/src/main/java/sansam/team/common/FileUploadUtil.java
  team/src/main/java/sansam/team/config/S3Config.java
  team/src/main/java/sansam/team/test/command/controllers/TestController.java
  team/src/main/resources/application.yml
Labels: FEAT, TEST

#21 [FEAT] 로그인 및 회원가입 API 구현 및 JWT 토큰 발급 작업 완료 + SpringSecurity 설정 중
  team/build.gradle
  team/src/main/java/sansam/team/Application.java
  team/src/main/java/sansam/team/common/JWTUtil.java
  team/src/main/java/sansam/team/config/SecurityConfig.java
  team/src/main/java/sansam/team/config/SwaggerConfig.java
  team/src/main/java/sansam/team/filter/JWTFilter.java
  team/src/main/java/sansam/team/filter/LoginFilter.java
  team/src/main/java/sansam/team/user/command/controller/UserController.java
  team/src/main/java/sansam/team/user/command/dto/JwtToken.java
  team/src/main/java/sansam/team/user/command/dto/LoginRequestDTO.java
  team/src/main/java/sansam/team/user/command/dto/LoginResponseDTO.java
  team/src/main/java/sansam/team/user/command/dto/UserDTO.java
  team/src/main/java/sansam/team/user/command/dto/UserJoinDTO.java
  team/src/main/java/sansam/team/user/command/entity/User.java
  team/src/main/java/sansam/team/user/command/enums/RoleType.java
  team/src/main/java/sansam/team/user/command/enums/StatusType.java
  team/src/main/java/sansam/team/user/command/repository/UserRepository.java
  team/src/main/java/sansam/team/user/command/service/UserService.java
  team/src/main/resources/application.yml
  team/src/main/resources/data.sql
  team/src/main/resources/schema.sql
Labels: BUG, FEAT, CHORE, REFACTOR, TEST

#25 [FEAT] 프로젝트 게시물 READ 작업
  team/src/main/java/sansam/team/common/embedded/Auditable.java
  team/src/main/java/sansam/team/common/embedded/AuditableEntity.java
  team/src/main/java/sansam/team/common/embedded/BaseEntity.java
  team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
  team/src/main/java/sansam/team/project/command/entity/ProjectBoard.java
  team/src/main/java/sansam/team/project/command/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardQueryController.java
  team/src/main/java/sansam/team/project/query/dto/ProjectBoardQueryDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectBoardMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectBoardQueryService.java
  team/src/main/resources/mapper/project/ProjectBoardMapper.xml
Labels: BUG, FEAT, CHORE, REFACTOR

#27 [FEAT] 프로젝트 게시물 CRUD 테스트 코드 추가
  team/src/main/java/sansam/team/project/command/dto/ProjectBoardDTO.java
  team/src/main/java/sansam/team/project/command/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/query/dto/ProjectBoardQueryDTO.java
  team/src/test/java/sansam/team/project/command/service/ProjectBoardServiceTest.java
  team/src/test/java/sansam/team/project/query/service/ProjectBoardQueryServiceTest.java
  team/src/test/java/sansam/team/test/command/service/TestServiceTest.java
  team/src/test/java/sansam/team/test/query/services/TestQueryServiceTest.java
Labels: FEAT, TEST

#29 [FEAT] 프로젝트 신청 회원 CUD 작업 및 테스트 코드 작성
  team/src/main/java/sansam/team/project/command/controller/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
  team/src/main/java/sansam/team/project/command/dto/projectboard/ProjectApplyMemberDTO.java
  team/src/main/java/sansam/team/project/command/dto/projectboard/ProjectBoardDTO.java
  team/src/main/java/sansam/team/project/command/entity/ProjectApplyMember.java
  team/src/main/java/sansam/team/project/command/entity/ProjectBoard.java
  team/src/main/java/sansam/team/project/command/enums/ApplyStatus.java
  team/src/main/java/sansam/team/project/command/repository/ProjectApplyMemberRepository.java
  team/src/main/java/sansam/team/project/command/service/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/service/ProjectBoardService.java
  team/src/main/java/sansam/team/user/command/entity/User.java
  team/src/test/java/sansam/team/project/command/service/ProjectApplyMemberServiceTest.java
  team/src/test/java/sansam/team/project/command/service/ProjectBoardServiceTest.java
Labels: FEAT, REFACTOR, TEST

#31 [FEAT] 프로젝트 신청 회원 READ 작업 및 테스트 코드 작성
  team/src/main/java/sansam/team/project/command/controller/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/controller/ProjectBoardController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectApplyMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardQueryController.java
  team/src/main/java/sansam/team/project/query/dto/projectboard/ApplyMemberQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectApplyMemberQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectBoardQueryDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectApplyMemberMapper.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectBoardMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectApplyMemberQueryService.java
  team/src/main/java/sansam/team/project/query/service/ProjectBoardQueryService.java
  team/src/main/resources/mapper/project/ProjectApplyMemberMapper.xml
  team/src/main/resources/mapper/project/ProjectBoardMapper.xml
  team/src/test/java/sansam/team/project/query/service/ProjectApplyMemberServiceTest.java
  team/src/test/java/sansam/team/project/query/service/ProjectBoardQueryServiceTest.java
Labels: FEAT, CHORE, TEST

#33 [FEAT] 프로젝트 엔티티 생성
  team/src/main/java/sansam/team/project/command/entity/Project.java
  team/src/main/java/sansam/team/project/command/enums/ProjectStatus.java
Labels: FEAT

#37 [FEAT] DDL 구문 완성
  team/src/main/resources/schema.sql
Labels: FEAT

#41 [REFACTOR] Auditable 수정
  team/src/main/java/sansam/team/Application.java
  team/src/main/java/sansam/team/common/BaseTimeEntity.java
  team/src/main/java/sansam/team/common/embedded/Auditable.java
  team/src/main/java/sansam/team/common/embedded/AuditableEntity.java
  team/src/main/java/sansam/team/common/embedded/BaseEntity.java
  team/src/main/java/sansam/team/test/command/entity/Test.java
Labels: FEAT, REFACTOR

#46 팀 채팅방 엔티티 생성
  team/src/main/java/sansam/team/project/command/dto/project/ProjectDTO.java
  team/src/main/java/sansam/team/project/command/entity/Project.java
  team/src/main/java/sansam/team/project/command/entity/ProjectMember.java
  team/src/main/java/sansam/team/project/command/repository/ProjectRepository.java
  team/src/main/java/sansam/team/project/command/service/ProjectService.java
  team/src/main/java/sansam/team/team/command/entity/Team.java
  team/src/main/java/sansam/team/team/command/entity/TeamChat.java
  team/src/test/java/sansam/team/project/command/service/ProjectServiceTest.java
Labels: FEAT

#49 Y/N 여부 Enum 클래스 생성
  team/src/main/java/sansam/team/common/Yn.java
  team/src/main/java/sansam/team/team/command/entity/TeamChat.java
Labels: FEAT

#52 [REFACTOR] 프로젝트 엔티티 수정 작업
  team/src/main/java/sansam/team/common/YesNo.java
  team/src/main/java/sansam/team/project/command/entity/Project.java
  team/src/main/java/sansam/team/project/command/entity/ProjectMember.java
  team/src/main/java/sansam/team/team/command/entity/TeamChat.java
Labels: CHORE, REFACTOR

#53 Team Member Entity 생성
  team/src/main/java/sansam/team/team/command/entity/Interest.java
  team/src/main/java/sansam/team/team/command/entity/TeamMember.java
Labels: FEAT

#55 팀 일정, 팀원 일정 진행상황 엔티티 추가
  team/src/main/java/sansam/team/team/command/entity/TeamMemberScheduleProgress.java
  team/src/main/java/sansam/team/team/command/entity/TeamSchedule.java
Labels: FEAT

#57 DDL 수정
  team/src/main/resources/schema.sql
Labels: FEAT

#61 [REFACTOR] User 엔티티 변경 및 엔티티 변경에 따른 다른 코드 변경
  team/src/main/java/sansam/team/common/jwt/JWTUtil.java
  team/src/main/java/sansam/team/filter/JWTFilter.java
  team/src/main/java/sansam/team/filter/LoginFilter.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/Project.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
  team/src/main/java/sansam/team/project/query/service/ProjectApplyMemberQueryService.java
  team/src/main/java/sansam/team/user/command/application/controller/UserController.java
  team/src/main/java/sansam/team/user/command/application/dto/JwtToken.java
  team/src/main/java/sansam/team/user/command/application/dto/LoginRequestDTO.java
  team/src/main/java/sansam/team/user/command/application/dto/LoginResponseDTO.java
  team/src/main/java/sansam/team/user/command/application/dto/UserDTO.java
  team/src/main/java/sansam/team/user/command/application/dto/UserJoinDTO.java
  team/src/main/java/sansam/team/user/command/application/service/UserService.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/RoleType.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/StatusType.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/java/sansam/team/user/command/domain/repository/UserRepository.java
  team/src/main/java/sansam/team/user/command/entity/User.java
  team/src/main/java/sansam/team/user/command/infrastructure/repository/JpaUserRepository.java
  team/src/main/java/sansam/team/user/command/repository/UserRepository.java
  team/src/test/java/sansam/team/project/command/application/service/ProjectApplyMemberServiceTest.java
  team/src/test/java/sansam/team/project/command/application/service/ProjectBoardServiceTest.java
  team/src/test/java/sansam/team/project/command/application/service/ProjectServiceTest.java
  team/src/test/java/sansam/team/project/query/service/ProjectApplyMemberServiceTest.java
Labels: REFACTOR

#63 [REFACTOR] 프로젝트 게시물 READ 작업 리펙토링
  team/src/main/java/sansam/team/project/command/application/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectBoard.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectBoardMapper.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardAdminController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardUserController.java
  team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectBoardAdminDTO.java
  team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectBoardAllQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/projectboard/ProjectBoardUserDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectBoardMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectBoardQueryService.java
  team/src/main/resources/mapper/project/ProjectBoardMapper.xml
  team/src/test/java/sansam/team/project/query/service/ProjectBoardQueryServiceTest.java
Labels: FEAT, CHORE, REFACTOR

#71 [REFACTOR] 프로젝트 게시물 READ 테스트 코드 수정
  team/src/main/java/sansam/team/project/command/application/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectBoard.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/test/java/sansam/team/project/command/application/service/ProjectBoardServiceTest.java
  team/src/test/java/sansam/team/project/query/service/ProjectBoardQueryServiceTest.java
Labels: CHORE, REFACTOR, TEST

#79 [FEAT] 프로젝트 CUD 작업 완료
  team/src/main/java/sansam/team/common/jwt/SecurityUtil.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectBoardController.java
  team/src/main/java/sansam/team/project/command/application/controller/ProjectController.java
  team/src/main/java/sansam/team/project/command/application/dto/project/ProjectCreateDTO.java
  team/src/main/java/sansam/team/project/command/application/dto/project/ProjectUpdateDTO.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/Project.java
  team/src/main/java/sansam/team/project/command/domain/repository/ProjectRepository.java
  team/src/main/resources/mapper/project/ProjectBoardMapper.xml
  team/src/main/resources/schema.sql
  team/src/test/java/sansam/team/project/command/application/service/ProjectApplyMemberServiceTest.java
  team/src/test/java/sansam/team/project/command/application/service/ProjectBoardServiceTest.java
  team/src/test/java/sansam/team/project/command/application/service/ProjectServiceTest.java
Labels: FEAT, REFACTOR

#85 [FEAT] Insert 구문 추가
  team/src/main/resources/data.sql
Labels: FEAT

#86 [FEAT] 프로젝트 READ 기능 구현
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
  team/src/main/java/sansam/team/project/query/controller/ProjectAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardUserQueryController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectUserQueryController.java
  team/src/main/java/sansam/team/project/query/dto/project/ProjectAdminQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/project/ProjectAllQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/project/ProjectUserQueryDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectQueryService.java
  team/src/main/resources/mapper/project/ProjectMapper.xml
  team/src/main/resources/schema.sql
Labels: FEAT, REFACTOR

#87 [FEAT] 프로젝트 회원 CUD 기능 구현 완료
  team/src/main/java/sansam/team/project/command/application/controller/ProjectMemberController.java
  team/src/main/java/sansam/team/project/command/application/dto/project/ProjectMemberUpdateDTO.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectBoardService.java
  team/src/main/java/sansam/team/project/command/application/service/ProjectMemberService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
  team/src/main/java/sansam/team/project/command/domain/repository/ProjectMemberRepository.java
  team/src/main/java/sansam/team/project/command/infrastructure/repository/JpaProjectMemberRepository.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectBoardMapper.java
  team/src/main/java/sansam/team/project/command/mapper/ProjectMemberMapper.java
  team/src/main/java/sansam/team/project/query/controller/ProjectBoardUserQueryController.java
Labels: FEAT, REFACTOR

#95 [REFACTOR] 프로젝트 도메인 디렉토리 구조 변경
  team/src/main/java/sansam/team/project/command/application/controller/board/ProjectApplyMemberController.java
  team/src/main/java/sansam/team/project/command/application/controller/board/ProjectBoardController.java
  team/src/main/java/sansam/team/project/command/application/controller/project/ProjectController.java
  team/src/main/java/sansam/team/project/command/application/controller/project/ProjectMemberController.java
  team/src/main/java/sansam/team/project/command/application/service/board/ProjectApplyMemberService.java
  team/src/main/java/sansam/team/project/command/application/service/board/ProjectBoardService.java
  team/src/main/java/sansam/team/project/command/application/service/project/ProjectMemberService.java
  team/src/main/java/sansam/team/project/command/application/service/project/ProjectService.java
  team/src/main/java/sansam/team/project/command/domain/repository/board/ProjectApplyMemberRepository.java
  team/src/main/java/sansam/team/project/command/domain/repository/board/ProjectBoardRepository.java
  team/src/main/java/sansam/team/project/command/domain/repository/project/ProjectMemberRepository.java
  team/src/main/java/sansam/team/project/command/domain/repository/project/ProjectRepository.java
  team/src/main/java/sansam/team/project/command/infrastructure/repository/board/JpaProjectApplyMemberRepository.java
  team/src/main/java/sansam/team/project/command/infrastructure/repository/board/JpaProjectBoardRepository.java
  team/src/main/java/sansam/team/project/command/infrastructure/repository/project/JpaProjectMemberRepository.java
  team/src/main/java/sansam/team/project/command/infrastructure/repository/project/JpaProjectRepository.java
  team/src/main/java/sansam/team/project/query/controller/board/ProjectApplyMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardUserQueryController.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectUserQueryController.java
Labels: REFACTOR

#93 [FEAT] 깃허브 API 연동
  team/build.gradle
  team/src/main/java/sansam/team/common/github/GithubUtil.java
  team/src/main/java/sansam/team/config/GithubConfig.java
  team/src/main/java/sansam/team/team/command/application/service/TeamService.java
  team/src/main/java/sansam/team/user/query/service/UserQueryService.java
  team/src/main/resources/application.yml
Labels: FEAT

#96 [FEAT] 커러어넷 API 연동
  team/build.gradle
  team/src/main/java/sansam/team/common/careernet/CareernetUtil.java
  team/src/main/java/sansam/team/config/CareernetConfig.java
  team/src/main/resources/application.yml
Labels: FEAT

#100 [REFACTOR] 팀원 컬럼 및 프로젝트 회원 컬럼 수정
  team/src/main/java/sansam/team/project/command/domain/aggregate/InterestType.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectApplyMember.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMember.java
  team/src/main/resources/data.sql
  team/src/main/resources/schema.sql
Labels: REFACTOR

#101 [FEAT MongoDB 연동 완료
  docker-compose.yml
Labels: FEAT

#107 [REFACTOR] 프로젝트 멤버 컬럼 수정
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/ProjectMember.java
  team/src/main/resources/data.sql
  team/src/main/resources/schema.sql
Labels: REFACTOR

#115 [FEAT] ResponseUtil 구현
  team/src/main/java/sansam/team/common/response/ApiResponse.java
  team/src/main/java/sansam/team/common/response/ResponseUtil.java
  team/src/main/java/sansam/team/exception/CustomException.java
  team/src/main/java/sansam/team/exception/CustomExceptionHandler.java
  team/src/main/java/sansam/team/exception/CustomNotFoundException.java
  team/src/main/java/sansam/team/exception/ErrorCodeType.java
  team/src/main/java/sansam/team/exception/ErrorResponseEntity.java
  team/src/main/java/sansam/team/exception/GlobalExceptionHandler.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
  team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
Labels: FEAT, REFACTOR

#123 [REFACTOR] 프로젝트 회원 별 전체/상세 조회 기능 수정
  team/src/main/java/sansam/team/project/query/controller/project/ProjectUserQueryController.java
  team/src/main/java/sansam/team/user/command/application/controller/mypagecontroller/MyPageController.java
  team/src/main/java/sansam/team/user/command/application/dto/mypagedto/MyPageDTO.java
  team/src/main/java/sansam/team/user/command/application/service/mypageservice/MyPageService.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/java/sansam/team/user/command/domain/repository/mypagerepository/MyPageRepository.java
  team/src/main/java/sansam/team/user/command/infrastructure/repository/JpaMyPageRepository.java
  team/src/main/resources/schema.sql
Labels: REFACTOR

#125 [REFACTOR] 프로젝트 READ 컨트롤러 반환값 수정
  team/src/main/java/sansam/team/project/command/application/controller/project/ProjectMemberController.java
  team/src/main/java/sansam/team/project/query/controller/board/ProjectApplyMemberQueryController.java
  team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardUserQueryController.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberAdminQueryCotroller.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberUserQueryController.java
  team/src/main/java/sansam/team/project/query/service/ProjectMemberQueryService.java
Labels: REFACTOR

#126 [FEAT] 프로젝트 멤버 READ 기능 구현 완료
  team/src/main/java/sansam/team/project/query/controller/board/ProjectBoardAdminQueryController.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberAdminQueryCotroller.java
  team/src/main/java/sansam/team/project/query/dto/project/ProjectMemberAdminAllQueryDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectMemberMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectMemberQueryService.java
  team/src/main/resources/mapper/project/ProjectMember.xml
Labels: FEAT

#130 [Feat] 팀 채팅 구현
  docker-compose.yml
  team/build.gradle
  team/src/main/java/sansam/team/common/mongo/MongoDBSequence.java
  team/src/main/java/sansam/team/common/mongo/MongoDBSequenceCreator.java
  team/src/main/java/sansam/team/common/websocket/WebSocketClient.java
  team/src/main/java/sansam/team/common/websocket/dto/TeamChatMemberDTO.java
  team/src/main/java/sansam/team/common/websocket/dto/TeamChatMessageDTO.java
  team/src/main/java/sansam/team/common/websocket/dto/TeamChatMessageType.java
  team/src/main/java/sansam/team/common/websocket/handler/WebSocketChatHandler.java
  team/src/main/java/sansam/team/config/MongoConfig.java
  team/src/main/java/sansam/team/config/WebSocketConfig.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatMessageController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatCreateRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatMessageCreateRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatMessageDTO.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatMessageDeleteRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatMessageType.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamChatUpdateRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamCreateRequest.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamUpdateRequest.java
  team/src/main/java/sansam/team/team/command/application/service/TeamChatMessageService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamChatService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamMemberService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamService.java
  team/src/main/java/sansam/team/team/command/domain/repository/TeamMemberRepository.java
  team/src/main/java/sansam/team/team/command/mapper/TeamChatMapper.java
  team/src/main/java/sansam/team/team/command/mapper/TeamMapper.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatMemberQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatQueryController.java
  team/src/main/java/sansam/team/team/query/dto/chat/TeamChatMemberRequest.java
  team/src/main/java/sansam/team/team/query/dto/chat/TeamChatMemberResponse.java
  team/src/main/java/sansam/team/team/query/dto/chat/TeamChatRequest.java
  team/src/main/java/sansam/team/team/query/dto/chat/TeamChatResponse.java
  team/src/main/java/sansam/team/team/query/dto/chat/TeamChatRoomRequest.java
  team/src/main/java/sansam/team/team/query/dto/chat/TeamChatRoomResponse.java
  team/src/main/java/sansam/team/team/query/mapper/TeamChatMemberQueryMapper.java
  team/src/main/java/sansam/team/team/query/mapper/TeamChatQueryMapper.java
  team/src/main/java/sansam/team/team/query/service/TeamChatMemberQueryService.java
  team/src/main/java/sansam/team/team/query/service/TeamChatQueryService.java
  team/src/main/resources/application.yml
  team/src/main/resources/mapper/team/TeamChatMapper.xml
  team/src/main/resources/mapper/team/TeamChatMemberMapper.xml
  team/src/main/resources/static/chat.html
Labels: FEAT

#131 [FEAT] 멘토 평가 CUD 기능 구현
  team/src/main/java/sansam/team/project/command/application/controller/mentor/MentorReviewController.java
  team/src/main/java/sansam/team/project/command/application/dto/mentor/MentorReviewDTO.java
  team/src/main/java/sansam/team/project/command/application/service/mentor/MentorReviewService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/MentorReview.java
  team/src/main/java/sansam/team/project/command/domain/repository/mentor/MentorReviewRepository.java
  team/src/main/java/sansam/team/project/command/infrastructure/repository/mentor/JpaMentorReviewRepository.java
  team/src/main/resources/schema.sql
Labels: FEAT, REFACTOR

#133 [FEAT] 팀 빌딩 알고리즘 작성
  team/src/main/java/sansam/team/common/github/GithubUtil.java
  team/src/main/java/sansam/team/project/command/domain/repository/project/ProjectMemberRepository.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamBuildingDTO.java
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMember.java
  team/src/main/java/sansam/team/team/command/domain/repository/TeamMemberRepository.java
  team/src/main/java/sansam/team/team/command/domain/repository/TeamReviewRepository.java
  team/src/main/java/sansam/team/user/command/domain/repository/UserRepository.java
  team/src/main/resources/data.sql
Labels: FEAT

#136 [REFACTOR] careernetUtil 수정
  team/src/main/java/sansam/team/common/careernet/CareernetUtil.java
Labels: REFACTOR

#139 [REFACTOR] URL 중복 수정
  team/src/main/java/sansam/team/team/query/controller/TeamChatMemberQueryController.java
Labels: REFACTOR

#142 [REFACTOR] URL 중복 수정
  team/src/main/java/sansam/team/team/query/controller/TeamChatQueryController.java
Labels: REFACTOR

#143 [FEAT] mongodb docker 재연동
  docker-compose.yml
Labels: FEAT

#150 [REFACTOR] user에 carreerMonth, careerYear 컬럼 추가
  team/src/main/java/sansam/team/user/command/application/dto/UserDTO.java
  team/src/main/java/sansam/team/user/command/application/dto/mypagedto/MyPageDTO.java
  team/src/main/java/sansam/team/user/command/domain/aggregate/entity/User.java
  team/src/main/resources/data.sql
  team/src/main/resources/schema.sql
Labels: REFACTOR

#151 Feat/major/#146 전공 CRUD 작업 및 커리어넷 api 연동
  team/src/main/java/sansam/team/major/command/application/controller/MajorController.java
  team/src/main/java/sansam/team/major/command/application/dto/MajorDTO.java
  team/src/main/java/sansam/team/major/command/application/service/MajorService.java
  team/src/main/java/sansam/team/major/command/domain/aggregate/Major.java
  team/src/main/java/sansam/team/major/command/domain/repository/MajorRepository.java
  team/src/main/java/sansam/team/major/command/infrastructure/JpaMajorRepository.java
  team/src/main/java/sansam/team/major/query/controller/MajorQueryController.java
  team/src/main/java/sansam/team/major/query/dto/MajorQueryDTO.java
  team/src/main/java/sansam/team/major/query/mapper/MajorQueryMapper.java
  team/src/main/java/sansam/team/major/query/service/MajorQueryService.java
Labels: FEAT, REFACTOR

#156 [FEAT] 팀빌딩 careerScore 계산 추가
  team/src/main/java/sansam/team/team/command/application/service/TeamBuildingService.java
Labels: FEAT

#158 [REFACTOR] Controller Response 수정
  team/src/main/java/sansam/team/common/websocket/handler/WebSocketChatHandler.java
  team/src/main/java/sansam/team/exception/CustomException.java
  team/src/main/java/sansam/team/exception/ErrorCodeType.java
  team/src/main/java/sansam/team/exception/GlobalExceptionHandler.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamChatMessageController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberController.java
  team/src/main/java/sansam/team/team/command/application/service/TeamChatMessageService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamChatService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamMemberService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamService.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatMemberQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamChatQueryController.java
  team/src/main/java/sansam/team/user/query/service/UserQueryService.java
Labels: REFACTOR

#159 [REFACTOR] 멘토 평가 CUD 엔드포인트 변경
  team/src/main/java/sansam/team/project/command/application/controller/mentor/MentorReviewController.java
  team/src/main/java/sansam/team/project/command/application/dto/mentor/MentorReviewCreateDTO.java
  team/src/main/java/sansam/team/project/command/application/dto/mentor/MentorReviewUpdateDTO.java
  team/src/main/java/sansam/team/project/command/application/service/mentor/MentorReviewService.java
  team/src/main/java/sansam/team/project/command/domain/aggregate/entity/MentorReview.java
  team/src/main/java/sansam/team/project/command/domain/repository/mentor/MentorReviewRepository.java
  team/src/main/java/sansam/team/project/query/controller/project/ProjectMemberUserQueryController.java
Labels: FEAT, REFACTOR

#165 [REFACTOR] 팀빌딩 컨트롤러 반환값 수정
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingController.java
Labels: REFACTOR

#166 Refactor/buildingrule/#153 팀빌딩 규칙 컨트롤러 리펙토링 및 리퀘스트매핑 수정
  team/src/main/java/sansam/team/buildingrule/command/application/controller/BuildingRuleController.java
  team/src/main/java/sansam/team/buildingrule/command/application/service/BuildingRuleService.java
  team/src/main/java/sansam/team/buildingrule/command/domain/aggregate/BuildingRule.java
  team/src/main/java/sansam/team/buildingrule/command/domain/repositroy/BuildingRuleRepository.java
  team/src/main/java/sansam/team/buildingrule/command/infrastructure/repository/JpaBuildingRuleRepository.java
  team/src/main/java/sansam/team/buildingrule/query/controller/BuildingRuleQueryController.java
  team/src/main/java/sansam/team/buildingrule/query/dto/BuildingRuleQueryDTO.java
  team/src/main/java/sansam/team/buildingrule/query/mapper/BuildingRuleQueryMapper.java
  team/src/main/java/sansam/team/buildingrule/query/service/BuildingRuleQueryService.java
  team/src/main/resources/mapper/buildingrule/BuildingRuleMapper.xml
Labels: CHORE, REFACTOR

#172 [FEAT] 수동 팀빌딩 기능 추가
  team/src/main/java/sansam/team/team/command/application/controller/TeamBuildingController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamMemberUpdateRequest.java
  team/src/main/java/sansam/team/team/command/application/service/TeamMemberService.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMember.java
  team/src/main/java/sansam/team/team/command/domain/repository/TeamMemberRepository.java
Labels: FEAT

#173 [FEAT] 프로젝트 강사 평가 READ 기능 구현
  team/src/main/java/sansam/team/project/command/application/controller/ProjectMentorReviewController.java
  team/src/main/java/sansam/team/project/query/controller/ProjectMentorReviewQueryController.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewAllQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewAllUserQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewQueryDTO.java
  team/src/main/java/sansam/team/project/query/dto/ProjectMentorReviewUserQueryDTO.java
  team/src/main/java/sansam/team/project/query/mapper/ProjectMentorReviewMapper.java
  team/src/main/java/sansam/team/project/query/service/ProjectMentorReviewQueryService.java
  team/src/main/resources/mapper/project/ProjectMentorReviewMapper.xml
Labels: FEAT

#174 [FEAT] 회원별 진행상황 입력, 추가, 삭제 및 강사 피드백 추가
  team/src/main/java/sansam/team/common/util/DateTimeUtil.java
  team/src/main/java/sansam/team/exception/ErrorCodeType.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamMemberScheduleController.java
  team/src/main/java/sansam/team/team/command/application/controller/TeamReviewController.java
  team/src/main/java/sansam/team/team/command/application/dto/TeamMemberScheduleDTO.java
  team/src/main/java/sansam/team/team/command/application/service/TeamMemberScheduleService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamReviewService.java
  team/src/main/java/sansam/team/team/command/application/service/TeamScheduleService.java
  team/src/main/java/sansam/team/team/command/domain/aggregate/entity/TeamMemberSchedule.java
  team/src/main/java/sansam/team/team/command/domain/repository/TeamMemberScheduleRepository.java
  team/src/main/java/sansam/team/team/query/controller/TeamQueryController.java
  team/src/main/java/sansam/team/team/query/controller/TeamScheduleQueryController.java
  team/src/main/java/sansam/team/team/query/mapper/TeamQueryMapper.java
  team/src/main/java/sansam/team/team/query/mapper/TeamScheduleQueryMapper.java
  team/src/main/java/sansam/team/team/query/service/TeamQueryService.java
  team/src/main/java/sansam/team/team/query/service/TeamScheduleQueryService.java
  team/src/main/resources/mapper/team/TeamMapper.xml
  team/src/main/resources/mapper/team/TeamScheduleMapper.xml
  team/src/main/resources/schema.sql
Labels: FEAT
